### ISSUE TITLE
[Feature] [VDP] [Pipelines] Workflow automation-Code Review Assistance

### ISSUE THREAD

**Issue by YCK1130** [instill-ai/instill-core#1025]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where do you intend to apply this feature?

Instill Core, Instill Cloud

### Is your Proposal Related to a Problem?

This is a sub-issue of #1022 
## User story
As an Engineering Manager

He/She wants a code review assistance tool that leverages Large Language Models (LLM) and other security tools

So that he/she can receive concise reports about file changes, identify important bugs or vulnerabilities quickly, and streamline the review process.

### **Background:**
Engineering managers often face the challenge of reading through a large volume of file changes during code reviews. This can lead to frustration and the risk of missing critical bugs or security vulnerabilities. An efficient tool that uses advanced technologies to summarize changes and highlight key issues can significantly improve the review process.

## **Basic Features:**
1. **Concise Summarization:**
   - The tool should utilize LLMs to generate concise and comprehensive summaries of file changes.
   - These summaries should highlight the most important changes, potential bugs, and security vulnerabilities.

2. **Automated Report Generation:**
   - Automatically generate detailed reports based on the LLM’s analysis of the code changes.
   - Reports should be easy to understand and provide actionable insights.

## **Advanced Features:**
3. **Developer Interaction:**
   - Allow developers to respond to the automatically generated reports.
   - Developers can address concerns, provide explanations, or make necessary changes based on the feedback from the report.

4. **Streamlined Review Process:**
   - Reduce the time spent on the review process by providing managers with a rough figure about the meaning and impact of code changes.
   - Enable quicker decision-making by presenting the most relevant information upfront.

5. **Security Integration:**
   - Incorporate other security tools to ensure that potential vulnerabilities are flagged and addressed.
   - Ensure that the tool is continuously updated with the latest security protocols and bug detection algorithms.

## **Benefits:**
- **Efficiency:** The tool saves time for engineering managers by summarizing large volumes of file changes.
- **Accuracy:** Reduces the risk of missing important bugs or vulnerabilities.
- **Responsiveness:** Facilitates quicker responses from developers, leading to faster iterations and improvements.
- **Security:** Enhances the overall security of the codebase by integrating advanced security tools.

### Anything Else?

**Scenario:**

1. **Initial Review:**
   - An engineering manager receives a notification about a new set of file changes.
   - The manager opens the tool and views a concise report generated by the LLM.

2. **Report Analysis:**
   - The report highlights several key changes, potential bugs, and a security vulnerability.
   - The manager quickly understands the overall impact of the changes and identifies areas of concern.

3. **Developer Response:**
   - The report is shared with the developers.
   - Developers review the report, provide explanations for the changes, and make necessary adjustments to address the identified issues.

4. **Final Review:**
   - The manager reviews the updated report and confirms that all concerns have been addressed.
   - The code is approved, and the review process is completed efficiently.

**Comment by chuang8511** [comment]
I closed this because it has been done by GitHub component
