### ISSUE TITLE
[GitHub] Add inputs to “Create Issue”  task “priority”, “label”, "assignee"

### ISSUE THREAD

**Issue by chuang8511** [instill-ai/instill-core#1095]
### Issue Description
**Current State**
- Currently, the [GitHub Component](https://www.instill.tech/docs/component/application/github#create-issue) on Instill VDP can carry out tasks like "Create Issue" but the input is limited to only customize title, body.
- Given this user story…
   - As a project manager
   - I want to automate unstructured slack messages into tickets  (i.e. slack -> OpenAI gpt-4o-mini -> Jira/GitHub)
   - So I want to use Application Components with AI Components
- it would be helpful to improve this component's "Create Issue" task to allow users to be able to create workflow automation with adding custom "label" and "assignee" too.

**Why We Want to Change?**
- Improve the GitHub Component "Create Issue" to allow for more inputs like "label", "assignee" so we can create more custom workflow automations

**Proposed Change**
- Check the GitHub Official [docs here]( https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue) and improve the component task for "Create Issue"

-------------------------------------------------------------------------------------------------------------------------

### Rules for the Component Hackathon
- Each issue will only be assigned to one person/team at a time.
- You can only work on one issue at a time.
- To express interest in an issue, please comment on it and tag @ShihChun-H, allowing the Instill AI team to assign it to you.
- Ensure you address all feedback and suggestions provided by the Instill AI team.
- If no commits are made within five days, the issue may be reassigned to another contributor.
- Join our Discord to engage in discussions and seek assistance in #hackathon channel. For technical queries, you can tag @chuang8511.

-------------------------------------------------------------------------------------------------------------------------

**[Component Contribution Guideline](https://github.com/instill-ai/pipeline-backend/blob/8f870f06b30c631c1c84556fdb95368cf32c7d00/.github/CONTRIBUTING.md) | [Documentation](https://www.instill.tech/docs/component/application/github) | [Official Go Tutorial
](https://go.dev/tour/welcome/1)**

**Comment by sajdakabir** [comment]
@kuroxx can i get some more info about this issue?

**Comment by MubeenKodvavi** [comment]
@ShihChun-H I will add labels and assignees field to github's component create issue task against this issue.
Please assign this issue to me.

**Comment by ShihChun-H** [comment]
Hi @MubeenKodvavi, sounds great! Issue has been assigned to you.
