### ISSUE TITLE
[Web] Align the web operator fields

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#1113]
### Issue Description
**Current State**
- The different tasks in web operator are not consistent in terms of fields.

**Proposed Change**
- Please adjust [crawling](https://www.instill.tech/docs/component/operator/web#crawl-website) by following the [scrape](https://www.instill.tech/docs/component/operator/web#scrape-webpage) .
  - `include-link-text` should be `include-markdown`. 
  - `link-text` should be `markdown`
  - Please remember to 
    1. modify the description for the modified fields as well.
    2. modify the version according to [sane-version-control](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/CONTRIBUTING.md#sane-version-control)
- Please add the migration file for us to update the recipes to avoid the current existing recipes.
  - You can refer to [here](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/db/migration/convert/convert000029/convert.go)
  - p.s. Now, the current script remove the memo in the recipe, which we want to avoid it. So, please come out a way to update the field name without editing original recipes.

-------------------------------------------------------------------------------------------------------------------------

### Rules for the Component Hackathon
- Each issue will only be assigned to one person/team at a time.
- You can only work on one issue at a time.
- To express interest in an issue, please comment on it and tag @ShihChun-H, allowing the Instill AI team to assign it to you.
- Ensure you address all feedback and suggestions provided by the Instill AI team.
- If no commits are made within five days, the issue may be reassigned to another contributor.
- Join our Discord to engage in discussions and seek assistance in #hackathon channel. For technical queries, you can tag @chuang8511.

-------------------------------------------------------------------------------------------------------------------------

**[Component Contribution Guideline](https://github.com/instill-ai/pipeline-backend/blob/8f870f06b30c631c1c84556fdb95368cf32c7d00/.github/CONTRIBUTING.md) | [Documentation](https://www.instill.tech/docs/component/operator/web) | [Official Go Tutorial
](https://go.dev/tour/welcome/1)**

**Comment by su-shubham** [comment]
Interested @ShihChun-H ! Working on this issue.

**Comment by ShihChun-H** [comment]
Hi @su-shubham, no problem! The issue has been assigned to you!

**Comment by kuroxx** [comment]
@chuang8511 Could you provide more details or direction on this one 🙏

**Comment by chuang8511** [comment]
Hi @su-shubham 
Sorry, the original task is outdated, and I have updated the new description.
Please feel free to let me know if you have further questions!

Thanks for your time! 🙇

**Comment by su-shubham** [comment]
Hello @ShihChun-H! Thanks for updating the issue. Could you provide more details on specifying the version for the current updates?

**Comment by chuang8511** [comment]
Hi @su-shubham , the details are updated in the issues.
Please read the [contribution guideline](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/CONTRIBUTING.md) to understand the product first.
Then, you will understand what the issue description means concretely.

Thank you for your question!

**Comment by kuroxx** [comment]
Hello @su-shubham, as I mentioned to you in our chat earlier, unfortunately, this issue has been deprecated due to on-going refactoring work... 

Apologies for any confusion and we appreciate your understanding 🙇 

I will now close this issue and hope you can pick another one to try 🙌
