### ISSUE TITLE
[Pinecone] Add rerank task

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#1114]
### Issue Description
**Current State***
- Current Pinecone does not support Rerank task

**Why We Want to Change?***
- Pinecone introduces the rerank API

**Proposed Change***
- Reduce the fields on the node.
- Mark the password as secret

-------------------------------------------------------------------------------------------------------------------------

### Rules for the Component Hackathon
- Each issue will only be assigned to one person/team at a time.
- You can only work on one issue at a time.
- To express interest in an issue, please comment on it and tag @kuroxx, allowing the Instill AI team to assign it to you.
- Ensure you address all feedback and suggestions provided by the Instill AI team.
- If no commits are made within five days, the issue may be reassigned to another contributor.
- Join our Discord to engage in discussions and seek assistance in #hackathon channel. For technical queries, you can tag @chuang8511.

-------------------------------------------------------------------------------------------------------------------------

**[Component Contribution Guideline](https://github.com/instill-ai/pipeline-backend/blob/8f870f06b30c631c1c84556fdb95368cf32c7d00/.github/CONTRIBUTING.md) | [Documentation](https://www.instill.tech/docs/component/data/pinecone) | [Official Go Tutorial
](https://go.dev/tour/welcome/1)**

**Comment by MubeenKodvavi** [comment]
@ShihChun-H

Please assign this task to me, I will add this functionility.
We need to leverage this API: https://docs.pinecone.io/reference/api/2024-10/inference/rerank

Some questions:
Pinecone is a data component. Do we need to rerank tasks through a data component?
Should we not introduce a seperate ai component for pinecone, or doing this with data is fine?

**Comment by MubeenKodvavi** [comment]
This should be integrated once rerank API is in stable release. 
Currently, the API is available in version `2024-10` of Pinecone API which is a release-candidate.

**Comment by ShihChun-H** [comment]
Hi @chuang8511, Could you help clarify the question raised by @MubeenKodvavi? Thanks!

**Comment by ShihChun-H** [comment]
Hi @MubeenKodvavi, thanks for your offer to take on this task. Currently, our policy allows only one assigned issue per contributor at a time. I’ll assign this to you as soon as your current task is completed. Thanks for understanding! 🙌🏻

**Comment by donch1989** [comment]
Hi @MubeenKodvavi 
Thank you for taking on this task. Although reranking is an advanced AI feature, it is frequently used in the scope of data operations. We believe it is still appropriate to include reranking in this data component as well.

**Comment by aazam-gh** [comment]
Hi, can I be assigned this issue :)

**Comment by ShihChun-H** [comment]
Hi @MubeenKodvavi, since you have already completed the issue assigned to you. Would you like to work on this issue next?

**Comment by ShihChun-H** [comment]
Hi @aazam-gh, there is a queue for this issue, would you mind waiting for a bit? 🙏

**Comment by aazam-gh** [comment]
Sure I'll look into other ones

**Comment by MubeenKodvavi** [comment]
@ShihChun-H 
As I mentioned before, this issue should be implemented when the Rerank API is available in the stable version of the Pinecone API.
Currently, Pinecone API defaults to the latest release version, which is 2024-07. However, the Rerank API is not available in this version.
We can specify the 2024-10 version in the headers if we need this feature before 2024-10 is stable.
![Image](https://github.com/user-attachments/assets/88e380a5-289e-48b4-9e6c-c688d4fe00d0)

You can assign this task to me, and I can raise a PR. However, I suggest waiting until the 2024-10 version is officially released before merging, as it is expected to be available by the end of this month. Reference: [Pinecone API Versioning ](https://docs.pinecone.io/reference/api/versioning)

**Comment by chuang8511** [comment]
> However, I suggest waiting until the 2024-10 version is officially released before merging, as it is expected to be available by the end of this month. Reference: [Pinecone API Versioning](https://docs.pinecone.io/reference/api/versioning)

Hi @MubeenKodvavi , thanks for reminding us! We will consider it when we review the PR.
For the assignment, I will leave it for @ShihChun-H to organise it.

**Comment by ShihChun-H** [comment]
Hi @MubeenKodvavi Totally understand the circumstance.
I will assign this issue to you, and you can submit the PR after the 2024-10 version is officially released. This ensures that the assignment remains with you throughout the process, and won't be taken away from you 🙌🏻

**Comment by kuroxx** [comment]
Hey @MubeenKodvavi how's it going? Just checking the status of this task - has there been any updates? 
In the meantime, feel free to join our Discord server to share & support others with component development: discord.gg/sevxWsqpGh

**Comment by MubeenKodvavi** [comment]
Hi @kuroxx , I will raise a PR for it this weekend.

**Comment by MubeenKodvavi** [comment]
@ShihChun-H @kuroxx can you request a review of linked PR from the team. Thank you :)

**Comment by kuroxx** [comment]
Hey @MubeenKodvavi yes will pass it on to the team!! Thanks for raising 🤝

**Comment by kuroxx** [comment]
Hey @MubeenKodvavi could you check the feedback in your PR and update accordingly, thanks! 🙇

**Comment by kuroxx** [comment]
Hey @MubeenKodvavi will you be able to address the feedback in your PR by the end of today? 

Hacktoberfest 2024 submissions are closing soon 🙇

**Comment by MubeenKodvavi** [comment]
@kuroxx yes, I will try to do it by end of today.

**Comment by MubeenKodvavi** [comment]
@kuroxx I understand that hacktoberfest is ending. Due to time constraints, I will complete this PR outside the scope of the event.
