### ISSUE TITLE
[Video] Video Component to extract 1 frame every N seconds

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#1115]
### Issue Description
**Current State**
- The Video Component minimum FPS is 1 (integer)

**Why We Want to Change?**
- For a use case like presentation in the video, I do not want to extract 1 frame every second but 1 frame every 10 seconds to save resources and reduce the number of images needed to feed into the next component.

**Proposed Change**
- Change FPS to accept fractional inputs i.e. 60, 30, 1, 1/2, 1/4, 1/30…

-------------------------------------------------------------------------------------------------------------------------

### Rules for the Component Hackathon
- Each issue will only be assigned to one person/team at a time.
- You can only work on one issue at a time.
- To express interest in an issue, please comment on it and tag @kuroxx, allowing the Instill AI team to assign it to you.
- Ensure you address all feedback and suggestions provided by the Instill AI team.
- If no commits are made within five days, the issue may be reassigned to another contributor.
- Join our Discord to engage in discussions and seek assistance in #hackathon channel. For technical queries, you can tag @chuang8511.

-------------------------------------------------------------------------------------------------------------------------

**[Component Contribution Guideline](https://github.com/instill-ai/pipeline-backend/blob/8f870f06b30c631c1c84556fdb95368cf32c7d00/.github/CONTRIBUTING.md) | [Documentation](https://www.instill.tech/docs/component/operator/video) | [Official Go Tutorial
](https://go.dev/tour/welcome/1)**

**Comment by samir-advantech** [comment]
I am interested in this issue @ShihChun-H

**Comment by ShihChun-H** [comment]
@samir-advantech Awesome! Let me assign this issue to you. Please make sure to read and follow the rules above 🙌🏻

**Comment by ShihChun-H** [comment]
Hi @samir-advantech, I'm following up to check on any progress made regarding this issue. Could you please provide an update? Thanks 🙏

**Comment by Reckadon** [comment]
Hi, @ShihChun-H ! If @samir-advantech is not available or working on this, can I work on this?

**Comment by kuroxx** [comment]
Hey @samir-advantech, since this issue has not been worked on for over >5 days, I will now assign this issue to @Reckadon 🙏  Thank you for your contribution attempt!

**Comment by Reckadon** [comment]
hi @kuroxx, thanks for letting me contribute.
I have managed to setup the project and start the development server on localhost, where can I find the login credentials? I can't find them on the repository

**Comment by kuroxx** [comment]
Hey @Reckadon, thanks for raising the issue! 

I saw your message on Discord - hope it can be resolved after adjusting the Docker resources : https://www.instill.tech/docs/core/deployment#docker-resource-requirements

**Comment by Reckadon** [comment]
do we want to accept inputs like 10, 30, 1/5, 1/10 only or, are pure numbers fine? like- 10, 30, 0.2, 0.1, 0.5

accepting both numbers and fractional strings will require the `type` field in `tasks.json` to be `any`.

**Comment by chuang8511** [comment]
> do we want to accept inputs like 10, 30, 1/5, 1/10 only or, are pure numbers fine? like- 10, 30, 0.2, 0.1, 0.5

It seems good that we can support 1/5 or 0.2.


> accepting both numbers and fractional strings will require the type field in tasks.json to be any.

Yes, please proceed this. Thanks for confirmation!

**Comment by chuang8511** [comment]
Oh, I did not notice it.
Could you try to set it as `string` first?

**Comment by kuroxx** [comment]
@chuang8511 @donch1989 please review when you are free 🙏  thank you!

**Comment by Reckadon** [comment]
please mark it as hacktoberfest-completed!
