### ISSUE TITLE
Enable autosave in a particular point

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#505]
Upon adding a new iterator, and going back to the console, the output is not shown at the bottom of the component. Need to save it in order to see the output. I suppose this will be solved after we have auto-save function. But I'm not sure when the auto-save feature would be implemented, so I was wondering if there's an easy-to-implement workaround here.

Decision: When the user goes back to the console by clicking the Console, frontend can include the auto-save function to solve the issue.

[Slack Message](https://instill-ai.slack.com/archives/C0649D73KUM/p1710918875370189?thread_ts=1710918875.370189&cid=C0649D73KUM)

**Comment by felixcorleone** [comment]
@ShihChun-H Auto-save is a planned new feature expected to be completed in 2 months. Therefore, I will close this issue for now.
