### ISSUE TITLE
[Improvement] Add Last Used date to the API Tokens page

### ISSUE THREAD

**Issue by kcl11** [instill-ai/instill-core#508]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Console

### Is your Proposal Related to a Problem?

I'd like to know which API token(s) can be deprecated/deleted.

### Describe Your Proposed Improvement

Add "Last Used" column to the API Tokens page

### Highlight the Benefits

To help users clean up their API tokens

**Comment by kcl11** [comment]
👍🏼

**Comment by felixcorleone** [comment]
@chuang8511 According to the Linear INS-3894 issue status, I have closed this issue.
cc @donch1989

**Comment by kuroxx** [comment]
Hello @kcl11, it's Anni from Instill AI. 

Thank you for your thoughtful suggestion, we appreciate your feedback to help improve this platform together 💪

We are happy to share this has now been implemented in the console! You should now see a `Last Used` column in the API Tokens page cc @chuang8511 @donch1989 

Feel free to raise any more questions or issues in the future. Happy building 🫶
