### ISSUE TITLE
[Improvement] improve zoom-in behavior in console pipeline builder

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill-core#510]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Console

### Is your Proposal Related to a Problem?

Upon zooming in on certain areas within the console pipeline builder, the entire page enlarges, affecting the top-right navigation, sometimes causing it to disappear. Through experimentation, I've observed that this issue occurs when zooming in on specific component areas, such as 

1. the end operator field under "See Result" mode and 
2. the output section of all components.

https://github.com/instill-ai/community/assets/66248476/3f2dd869-00b3-4dfb-90f9-10892cf99e8d

### Describe Your Proposed Improvement

I propose investigating the root cause of this behavior. Why do only certain fields exhibit this undesired enlargement effect?

### Highlight the Benefits

Identifying and addressing the cause of this issue will lead to improvements in the affected fields, enhancing the overall user experience.

**Comment by felixcorleone** [comment]
@xiaofei-du Given that this issue hasn't been updated for a long time and we now have new product plans, I will close this request and the corresponding GitHub issue. If the need arises again, please update the latest requirements and status according to the current situation.
