### ISSUE TITLE
[Improvement] align the order of user defined end component's field and the output field

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/instill-core#511]
## Tested by owner on d0

[CleanShot 2024-05-16 at 17.48.38.mp4](https://uploads.linear.app/52f06d0d-2381-411e-a8c5-7b375e3a0114/0593eea2-d17c-48da-8108-3745e537c0e6/972af005-c8b5-478d-a4e1-604a9ae9db49?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUyZjA2ZDBkLTIzODEtNDExZS1hOGM1LTdiMzc1ZTNhMDExNC8wNTkzZWVhMi1kMTdjLTQ4ZGEtODEwOC0zNzQ1ZTUzN2MwZTYvOTcyYWYwMDUtYzhiNS00NzhkLWE0ZTEtNjA0YTlhZTlkYjQ5IiwiaWF0IjoxNzE1ODUzMTI1LCJleHAiOjMzMjg2NDEzMTI1fQ.-uEySrM1_MweTKLeT7fslrT97LDVb2th2v6EbkK9liU)

### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Console

### Is your Proposal Related to a Problem?

Right now the end component's fields order are not represented on the output of the pipeline.

[https://github.com/instill-ai/community/assets/57251712/9f6e0c6c-edbd-4220-adcd-e0bc92a86eaf](https://github.com/instill-ai/community/assets/57251712/9f6e0c6c-edbd-4220-adcd-e0bc92a86eaf)

### Describe Your Proposed Improvement

We need to make the UI layer represent user defined order

### Highlight the Benefits

*No response*

### Anything Else?

*No response*

**Comment by felixcorleone** [comment]
@EiffelFly Since the issue has been done, and passed by the UAT, I'll close this issue. Thanks for your contribution.

CleanShot 2024-05-17 at 14.14.21.mp4
