### ISSUE TITLE
[Bug] The layout of nodes on pipeline preview and pipeline builder is not consistent even we have store the layout information

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/instill-core#512]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where did you encounter this bug?

Console

### Describe the Bug

The layout of nodes on pipeline preview and pipeline builder is not consistent even we have store the layout information

![CleanShot 2024-02-21 at 04 23 15](https://github.com/instill-ai/community/assets/57251712/afee15b2-dc42-444b-985b-d636ad71f7be)
![CleanShot 2024-02-21 at 04 22 18](https://github.com/instill-ai/community/assets/57251712/ed2c159e-4b78-461e-8d80-70e276a88d40)

### Expected Behavior

The layout should be consistent once the user store the layout infromation

**Comment by felixcorleone** [comment]
@EiffelFly Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
