### ISSUE TITLE
[Improvement] Improve long text field editing experience

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill-core#516]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Console

### Is your Proposal Related to a Problem?

https://github.com/instill-ai/community/assets/66248476/fe7ed9d1-e0a7-4499-8073-bbf92b258689

I encounter several frustrations when using long text fields:

- Inability to use `Enter` to add space between lines.
- The long text field still has the jumping issue when editing. Kind of hard to record the video for the problem but it happens 4 out of 5 when I type in a long text field for a long and complex prompt.
- Lack of support for using the right scroll to locate specific texts efficiently. Need to use keys `Up` and `Down`.

### Describe Your Proposed Improvement

- Enable support for adding space between lines or provide comprehensive editing features.
- Resolve the jumping issue during editing.
- Implement functionality for quickly locating specific texts without relying solely on keyboard navigation.

### Highlight the Benefits

Better text editing UX

**Comment by felixcorleone** [comment]
@EiffelFly As we've completed the following tasks, I will change the issue Close as Completed. Thanks for your contribution!

- Fix user can not use wheel scroll up and down on long text input
- Fix user can not key-down enter on the TextArea input in the pipeline builder
- Investigate the better enter experience for smart-hint related TextArea
