### ISSUE TITLE
[Bug] creating model which has cached will cause nil pointer err

### ISSUE THREAD

**Issue by heiruwu** [instill-ai/instill-core#534]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where did you encounter this bug?

Instill Core

### Describe the Bug

when creating a model which it's model weight its still cached in the model-backend, will cause nil pointer err

### Steps to Reproduce

1. create a model from `github`
2. deploy the model
3. delete the model
4. create the same model again
5. system 

### Actual Result

status 500 from the create model request

### Expected Behavior

status 200

**Comment by felixcorleone** [comment]
@heiruwu Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
