### ISSUE TITLE
[Improvement] Add a filter for displaying "All" pipelines on console

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#535]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Console

### Is your Proposal Related to a Problem?

There are filters for "Public" and "Private" pipelines. We need a filter for "ALL" pipelines

<img width="463" alt="image" src="https://github.com/instill-ai/community/assets/143982976/3e1fef16-e9a6-44de-b1c1-25a810bc8da0">

### Describe Your Proposed Improvement

Add a filter for displaying "All" pipelines on console

**Comment by felixcorleone** [comment]
@ShihChun-H The issue has completed.Thank you for the suggestion; it greatly improves the user experience.
![CleanShot 2024-07-29 at 02 17 47@2x](https://github.com/user-attachments/assets/de840348-3592-47a4-9984-3e88dc9cbf84)
