### ISSUE TITLE
[Improvement] Stability AI Connector default width and height can cause error

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#537]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Instill Core

### Is your Proposal Related to a Problem?

The default value of width and height is 512. But it will cause error since most of the model don't accept it.

### Describe Your Proposed Improvement

Update the default value of width and height to 1024

**Comment by felixcorleone** [comment]
@donch1989 The issue has been implemented in Sprint 37. And I'll close it.
