### ISSUE TITLE
[Improvement] Fetch the table schema from BigQuery

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#542]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Instill Core

### Is your Proposal Related to a Problem?

In the current BigQuery connector, the data input is freeform. The users might not know how to provide the correct data.

### Describe Your Proposed Improvement

1. Fetch the schema from BigQuery
2. Map the BigQuery data type to InstillFormat
3. Embed the data schema directly in the component JSON schema, so the user can see them on Console

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
