### ISSUE TITLE
[Bug] connector delete modal closed unexpectedly

### ISSUE THREAD

**Issue by pinglin** [instill-ai/instill-core#551]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where did you encounter this bug?

Console

### Describe the Bug

The delete modal is closed when the previous notification finishing.

https://github.com/instill-ai/community/assets/628430/b512c73c-e93a-431d-8c4d-5a3d70004cfb

### Steps to Reproduce

1. Delete a connector
2. Delete another connector and wait for the previous notification gone

### Actual Result

The latest delete modal will be closed surprisingly

### Expected Behavior

The latest delete modal should get unaffected by the previous operation

**Comment by felixcorleone** [comment]
@pinglin Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
