### ISSUE TITLE
[Improvement] make the hub pipeline input and output image size consistent

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill-core#559]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Instill Cloud

### Is your Proposal Related to a Problem?

The size of the input image and the output image is not consistent. 

![image](https://github.com/instill-ai/community/assets/66248476/aca4c4b8-af4f-4361-bb82-fe04b343c275)

### Describe Your Proposed Improvement

 Keep the size of the same data type consistent.

### Highlight the Benefits

Improve the UI

**Comment by felixcorleone** [comment]
@xiaofei-du Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
