### ISSUE TITLE
[Improvement] <onboarding> Improve the hint when user creating their user name

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/instill-core#560]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Instill Core

### Is your Proposal Related to a Problem?

Users got struck at the onboarding form and misunderstand that the username input is a input they need to fill in

### Describe Your Proposed Improvement

- Remove the instill.tech namespace
- Make it act like GitHub way of doing things, hint user the full URL like `https://instill.tech/<your_username>`

### Highlight the Benefits

Clear Hint, better user experience

**Comment by felixcorleone** [comment]
@EiffelFly Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
