### ISSUE TITLE
[Improvement] remove insecurity verification setting in Instill Model connector

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#561]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where are you aiming to make improvements?

Instill Core

### Is your Proposal Related to a Problem?

[Related discussion](https://github.com/instill-ai/connector/pull/92#discussion_r1443119756)

Using insecure TLS verification in a connection is not a good practice. The default setting for `InsecureSkipVerify` should be `false`, and we should connector configuration to set it to `true` only when necessary.

### Describe Your Proposed Improvement

- make `InsecureSkipVerify` as a setting in Instill Model connector configuration.

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
