### ISSUE TITLE
[INS-2349] [Bug] Deploy and undeploy local instance first causing "ERROR: instance 'localhost:8080' does not exists" whtn auth login later

### ISSUE THREAD

**Issue by pinglin** [instill-ai/instill-core#601]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill CLI

### Describe the Bug

The current implementation initiates the `default_hostname` configuration value with `api.instill.tech` only when running `inst auth login` and `~~/.config/instill/hosts.yml` being yet created.

If the user run `inst local deploy` and `inst local undeploy` in the very beginning, the `default_hostname` configuration value will be set to `localhost:8080` and the unregistration function won't delete `~~/.config/instill/hosts.yml` and will leave the `default_hostname` unchanged. This will cause the following `inst auth login` failing with `ERROR: instance 'localhost:8080' does not exists`.

### Steps to Reproduce

1. `brew install instill-ai/tap/inst`
2. `inst local deploy`
3. `inst local undeploy`
4. `inst auth login`

### Actual Result

Resulting in `ERROR: instance 'localhost:8080' does not exists`

### Expected Behavior

`inst auth login` should fallback to user the default api.instlil.tech host configuration.

### Technical Details

* **Project version**: v0.1.0-alpha
* **OS**: macOS

### Anything Else?

No

<sub>From [SyncLinear.com](https://synclinear.com) | [INS-2349](https://linear.app/instill-ai/issue/INS-2349/[bug]-deploy-and-undeploy-local-instance-first-causing-error-instance)</sub>

**Comment by felixcorleone** [comment]
@pinglin Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
