### ISSUE TITLE
[INS-2334] [Improvement] improve the component contribution workflow

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#602]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

Need to improve the contribution guideline for components (connectors and operators)

### Describe Your Proposed Improvement

- [ ] Update contribution guideline in [component](https://github.com/instill-ai/component)
- [ ] Add more comments in any component, such as [base64 operator](https://github.com/instill-ai/operator) as a example implementation.
- [ ] Design a testing framework for all component implementation

### Highlight the Benefits

*No response*

### Anything Else?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [INS-2334](https://linear.app/instill-ai/issue/INS-2334/[improvement]-improve-the-component-contribution-workflow)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
