### ISSUE TITLE
[INS-2137] [Improvement] Define a json-schema to validate component `definition.json`

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#638]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

For all connectors and operators, we have a `definition.json` file to define the spec of the component. But we don't have a way to validate the correctness of the `definition.json` file. 

We should provide a way to validate the `definition.json` file. 

### Describe Your Proposed Improvement

We can define a json-schema file that is used for validating all connector and operator `definition.json` file. 

<sub>[INS-2137](https://linear.app/instill-ai/issue/INS-2137/[improvement]-define-a-json-schema-to-validate-component)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
