### ISSUE TITLE
[INS-2136] [Feature] Get billing or usage information from vendor

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#639]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

In VDP, connector relies on the computation or storage resources provided by vendors. This will incur associated costs on vendor side.

We need to find a way to show the cost in VDP since VDP is a centric point of these connectors.

### Describe Your Proposed Solution

There are two possible ways to implement this.
1. We can have a function in side `IConnector` interface defined in `component` repo. And all connector implementation can implement this function to fetch the billing/cost/balance data from vendor.
2. We can have a function that can collect the cost of each trigger/execution for connector if possible.

<sub>[INS-2136](https://linear.app/instill-ai/issue/INS-2136/[feature]-get-billing-or-usage-information-from-vendor)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
