### ISSUE TITLE
[INS-2135] [Feature] Codec Operator

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#640]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

For image, video and audio, they have a lot of kinds of codec format, e.g. `jpg`, `png`, `h264`, `h265`, `wmv`, `mp3`, `aac`. 

Each connector have different codec requirement for its input/output, we need to have a convertor to handle the format conversion in order to let two components with different codec requirements can be connected.

### Describe Your Proposed Solution

We can implement a Codec Operator to handle the conversion.
For example, we can setup a Operator with configuration like this
```
{
  "input": {
    "input_format": "jpg",
    "output_format": "png",
    "input_data": "{ start.image }"
  }
}
```

<sub>[INS-2135](https://linear.app/instill-ai/issue/INS-2135/[feature]-codec-operator)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
