### ISSUE TITLE
[INS-2134] [Feature] Support upload any kind of data to Numbers blockchain

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#641]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

Currently, the Numbers Connector only allow upload image data to Numbers blockchain. Theoretically, the Numbers blockchain should accept any kind of data. (e.g. text, audio)

We should add this ability into Numbers Connector

### Describe Your Proposed Solution

We should remove the image constraint in Numbers Connector and make it accept all kinds of data as asset

<sub>[INS-2134](https://linear.app/instill-ai/issue/INS-2134/[feature]-support-upload-any-kind-of-data-to-numbers-blockchain)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
