### ISSUE TITLE
[INS-2132] [Improvement] Upload image assets to Numbers blockchain in parallel

### ISSUE THREAD

**Issue by donch1989** [instill-ai/instill-core#643]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

Currently, in [connector-blockchain](https://github.com/instill-ai/connector-blockchain), we upload the image to Numbers sequentially, which is slow.

We should optimize the upload image function to be executed in parallel.

### Describe Your Proposed Improvement

Use goroutine to upload images in parallel.

### Highlight the Benefits

If there are `N` images to be uploaded, we can reduce the time from `N*t` to `t`

<sub>[INS-2132](https://linear.app/instill-ai/issue/INS-2132/[improvement]-upload-image-assets-to-numbers-blockchain-in-parallel)</sub>

**Comment by felixcorleone** [comment]
@donch1989 Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
