### ISSUE TITLE
Improve http response codes

### ISSUE THREAD

**Issue by pinglin** [instill-ai/instill-core#851]
Creation endpoint should return 201 instead of 200. 

[gRPC-Gateway](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#controlling-http-response-status-codes) provides rpc option for precise http response definition.

**Comment by felixcorleone** [comment]
@pinglin Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
