### ISSUE TITLE
Upload auto-gen Swagger files to public buckets

### ISSUE THREAD

**Issue by pinglin** [instill-ai/instill-core#855]
We currently commit the auto-gen swagger files in this repository but a better CD flow would be to push the files to a remote bucket with a versioning filename, so this repository doesn't need to keep the auto-gen files in the commit history.

**Comment by felixcorleone** [comment]
@pinglin Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
