### ISSUE TITLE
Auto-merge protogen-* release PRs triggered by the release of protobufs

### ISSUE THREAD

**Issue by pinglin** [instill-ai/instill-core#856]
We need to manually merge the release PRs in `protogen-*` repositories at the moment. 

A better approach for the flow would be to auto-merge those release PRs.

**Comment by felixcorleone** [comment]
@pinglin Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
