### ISSUE TITLE
OpenAPI documentation is out of date in docker-compose

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill-core#875]
Current redoc deploys the OpenAPI docs from the `main` branch of the protobufs.
It should deploy the corresponding OpenAPI docs that are compatible with the `pipeline-backend` and `model-backend` in the docker-compose.yml.

**Comment by felixcorleone** [comment]
@pinglin @xiaofei-du Considering that the latest update time for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
